// packages/react-flicking/src/react-flicking/Flicking.tsx
/*
 * Copyright (c) 2015 NAVER Corp.
 * egjs projects are licensed under the MIT license
 */
import * as React from "react";
import ListDiffer, { DiffResult } from "@egjs/list-differ";
import VanillaFlicking, {
  FlickingOptions,
  EVENTS,
  withFlickingMethods,
  sync,
  getRenderingPanels,
  Plugin
} from "@egjs/flicking";
import { isFragment } from "react-is";

import { DEFAULT_PROPS, SLOT_VIEWPORT } from "./consts";
import { FlickingProps } from "./types";
import ReactRenderer from "./ReactRenderer";
import ReactPanelComponent from "./ReactPanelComponent";
import NonStrictPanelComponent from "./NonStrictPanelComponent";
import StrictPanelComponent from "./StrictPanelComponent";

class Flicking extends React.Component<Partial<FlickingProps & FlickingOptions>> {
  public static defaultProps: FlickingProps = DEFAULT_PROPS;

  @withFlickingMethods private _vanillaFlicking: VanillaFlicking;
  private _panels: React.RefObject<ReactPanelComponent>[] = [];
  private _pluginsDiffer: ListDiffer<any>;
  private _jsxDiffer: ListDiffer<React.ReactElement>;
  private _viewportElement: HTMLElement;
  private _diffResult: DiffResult<React.ReactElement> | null;
  private _mounted: boolean;
  private _renderCallback: () => any;

  public get mounted() { return this._mounted; }
  public get reactPanels() { return this._panels.map(panel => panel.current!); }

  public constructor(props) {
    super(props);

    this._panels = this._getChildren().map(() => React.createRef());
  }

  public setRenderCallback(callback: () => any) {
    this._renderCallback = callback;
  }

  public componentDidMount() {
    this._mounted = true;

    const props = this.props as Required<FlickingProps>;

    const flicking = new VanillaFlicking(
      this._viewportElement,
      {
        ...props,
        ...{ renderExternal: {
          renderer: ReactRenderer as any,
          rendererOptions: { reactFlicking: this }
        }}
      },
    );

    this._vanillaFlicking = flicking;
    this._bindEvents();

    const children = this._getChildren();
    this._jsxDiffer = new ListDiffer(children, panel => panel.key!);
    this._pluginsDiffer = new ListDiffer<any>();

    this._checkPlugins();
  }

  public componentWillUnmount() {
    this._mounted = false;

    this._vanillaFlicking.destroy();
  }

  public shouldComponentUpdate(nextProps: this["props"]) {
    const children = this._getChildren(nextProps.children);
    const diffResult = this._jsxDiffer.update(children);

    this._panels = children.map(() => React.createRef());
    this._diffResult = diffResult;

    return true;
  }

  public componentDidUpdate() {
    const flicking = this._vanillaFlicking;
    const diffResult = this._diffResult;

    this._checkPlugins();
    this._renderCallback && this._renderCallback();

    if (!diffResult || !flicking.initialized) return;

    sync(flicking, diffResult, this.reactPanels);

    if (diffResult.added.length > 0 || diffResult.removed.length > 0) {
      this.setState({});
    }

    this._diffResult = null;
  }

  public render() {
    const props = this.props;
    const Viewport = props.viewportTag as any;
    const Camera = props.cameraTag as any;
    const attributes: { [key: string]: any } = {};
    const flicking = this._vanillaFlicking;

    for (const name in props) {
      if (!(name in DEFAULT_PROPS) && !(name in VanillaFlicking.prototype)) {
        attributes[name] = props[name];
      }
    }

    const viewportClasses: string[] = ["flicking-viewport"];
    const isHorizontal = flicking
      ? flicking.horizontal
      : props.horizontal ?? true;

    if (!isHorizontal) {
      viewportClasses.push("vertical")
    }
    if (attributes.className) {
      viewportClasses.push(attributes.className);
    }

    const children = (this._diffResult && flicking && flicking.initialized)
      ? getRenderingPanels(flicking, this._diffResult)
      : this._getChildren();
    const panels = this.props.useFindDOMNode
      ? children.map((child, idx) => <NonStrictPanelComponent key={child.key!} ref={this._panels[idx]}>{child}</NonStrictPanelComponent>)
      : children.map((child, idx) => <StrictPanelComponent key={child.key!} ref={this._panels[idx] as any}>{child}</StrictPanelComponent>)

    return (
      <Viewport {...attributes} className={viewportClasses.join(" ")} ref={(e?: HTMLElement) => {
        e && (this._viewportElement = e);
      }}>
        <Camera className="flicking-camera">
          { panels }
        </Camera>
        { this._getViewportSlots() }
      </Viewport>
    );
  }

  private _bindEvents() {
    const flicking = this._vanillaFlicking!;
    const props = this.props as Required<FlickingProps>;

    Object.keys(EVENTS).forEach((eventKey: keyof typeof EVENTS) => {
      const eventName = EVENTS[eventKey];
      const propName = `on${eventName.charAt(0).toUpperCase() + eventName.slice(1)}`;

      flicking.on(eventName, e => {
        e.currentTarget = this;

        props[propName](e);
      });
    });

    flicking.once(EVENTS.READY, () => {
      this.forceUpdate();
    });
  }

  private _checkPlugins() {
    const { list, added, removed, prevList } = this._pluginsDiffer.update(this.props.plugins!) as DiffResult<Plugin>;

    this._vanillaFlicking.addPlugins(...added.map(index => list[index]));
    this._vanillaFlicking.removePlugins(...removed.map(index => prevList[index]));
  }

  private _getChildren(children: React.ReactNode = this.props.children) {
    return (React.Children.toArray(children) as Array<React.ReactElement<any>>)
      .filter(child => {
        return child.props.slot !== SLOT_VIEWPORT;
      })
      .reduce((all, child) => {
        return [...all, ...this._unpackFragment(child)];
      }, []) as Array<React.ReactElement<any>>;
  }

  private _getViewportSlots() {
    return (React.Children.toArray(this.props.children) as Array<React.ReactElement<any>>)
      .filter(child => {
        return child.props.slot === SLOT_VIEWPORT;
      })
  }

  private _unpackFragment(child: React.ReactElement) {
    return isFragment(child)
      ? React.Children.toArray(child.props.children)
        .reduce((allChilds, fragChild) => [...allChilds, ...this._unpackFragment(fragChild)], [])
      : [child];
  }
}

interface Flicking extends React.Component<Partial<FlickingProps & FlickingOptions>>, VanillaFlicking { }
export default Flicking;

// packages/vue-flicking/src/Flicking.vue
<template>
  <component :is="this.viewportTag" :class="{'flicking-viewport': true, 'vertical': this.vertical}">
    <component :is="this.cameraTag" class="flicking-camera">
      <VNodes :vnodes="this._panels" />
    </component>
  </component>
</template>
<script lang="ts">
/**
 * Copyright (c) 2015 NAVER Corp.
 * egjs projects are licensed under the MIT license
 */
import NativeFlicking, {
  EVENTS,
  FlickingOptions,
  withFlickingMethods,
  sync,
  getRenderingPanels,
  Plugin,
  Status
} from "@egjs/flicking";
import { ComponentEvent } from "@egjs/component";
import ListDiffer, { DiffResult } from "@egjs/list-differ";
import { Component, Vue, Prop } from "vue-property-decorator";
import { VNode } from "vue";

import VNodes from "./VNodes";

@Component({
  components: {
    VNodes
  }
})
class Flicking extends Vue {
  // Tag of the viewport element
  @Prop({ type: String, default: "div", required: false }) public viewportTag!: string;
  // Tag of the camera element
  @Prop({ type: String, default: "div", required: false }) public cameraTag!: string;
  @Prop({ type: Object, default: () => ({}), required: false }) public options!: Partial<FlickingOptions>;
  @Prop({ type: Array, default: () => ([]), required: false }) public plugins!: Plugin[];
  @Prop({ type: Object, required: false }) public status!: Partial<Status>;

  public get vertical() {
    const flicking = this._nativeFlicking;
    const isHorizontal = flicking
      ? flicking.horizontal
      : this.options.horizontal ?? true;

    return !isHorizontal;
  }

  private _panels: VNode[] = [];

  @withFlickingMethods private _nativeFlicking!: NativeFlicking;
  private _pluginsDiffer!: ListDiffer<any>;
  private _slotDiffer!: ListDiffer<VNode>;
  private _diffResult: DiffResult<VNode> | null = null;

  public created() {
    this._fillKeys();

    const slots = this._getSlots();
    this._panels = [...slots];
  }

  public mounted() {
    const options = {...this.options, ...{ renderExternal: true }};
    const viewportEl = this.$el as HTMLElement;
    const flicking = new NativeFlicking(viewportEl, options);
    this._nativeFlicking = flicking;

    if (flicking.initialized) {
      this.$emit(EVENTS.READY, { ...new ComponentEvent(EVENTS.READY), currentTarget: this });
    }

    const slots = this._getSlots();
    this._slotDiffer = new ListDiffer<VNode>(slots, vnode => vnode.key!);
    this._pluginsDiffer = new ListDiffer<Plugin>();

    this._bindEvents();
    this._checkPlugins();
    if (this.status) {
      flicking.setStatus(this.status);
    }

    this.$forceUpdate();
  }

  public beforeDestroy() {
    this._nativeFlicking.destroy();
  }

  public beforeUpdate() {
    this._fillKeys();

    const slots = this._getSlots();
    const diffResult = this._slotDiffer.update(slots);
    const flicking = this._nativeFlicking!;

    this._diffResult = diffResult;
    this._panels = flicking.initialized
      ? getRenderingPanels(flicking, diffResult)
      : slots;
  }

  public updated() {
    const flicking = this._nativeFlicking;
    const diffResult = this._diffResult;

    if (!diffResult) return;

    sync(flicking, diffResult);

    this._checkPlugins();

    if (diffResult.added.length > 0 || diffResult.removed.length > 0) {
      this.$forceUpdate();
    }

    this._diffResult = null;
  }

  private _bindEvents() {
    const flicking = this._nativeFlicking;
    const events = Object.keys(EVENTS).map((key: keyof typeof EVENTS) => EVENTS[key]);

    events.forEach(eventName => {
      flicking.on(eventName, (e: any) => {
        e.currentTarget = this;
        // Make events from camelCase to kebab-case
        this.$emit(eventName.replace(/([A-Z])/g, "-$1").toLowerCase(), e);
      });
    });

    if (this.options.renderOnlyVisible) {
      flicking.on(EVENTS.VISIBLE_CHANGE, e => {
        this.$forceUpdate();
      });
    }
    if (this.options.circular) {
      flicking.renderer.elementManipulator.on("orderChanged", () => {
        this.$forceUpdate();
      });
    }
  }

  private _checkPlugins() {
    const { list, added, removed, prevList } = this._pluginsDiffer.update(this.plugins);

    this._nativeFlicking.addPlugins(...added.map(index => list[index]));
    this._nativeFlicking.removePlugins(...removed.map(index => prevList[index]));
  }

  private _getSlots() {
    // Only elements are allowed as panel
    return this.$slots.default
      ? this.$slots.default.filter(slot => slot.tag)
      : [];
  }

  private _fillKeys() {
    const vnodes = this._getSlots();

    vnodes.forEach((node, idx) => {
      if (node.key == null) {
        node.key = `$_${idx}`;
      }
    });
  }
}

interface Flicking extends NativeFlicking {}
export default Flicking;
</script>
<style>
@import url("../node_modules/@egjs/flicking/dist/flicking.css");
</style>
