// packages/react-flicking/src/demo/features/Image.tsx

import * as React from "react";
import Flicking from "../../react-flicking/Flicking";
import "../css/infinite.css";

export default class ImageLoadDemo extends React.Component<{}, { show: boolean }> {
  public state = {
    show: false
  };

  public render() {
    console.log("rendering")
    return (
      <div id="image" className="container">
        <button onClick={() => { this.setState({ show: true }); }}>Click me</button>
        {this.state.show && <Flicking circular={true} duration={300} resizeOnContentsReady={true}>
            <img src="https://picsum.photos/seed/1/200/300" />
            <img src="https://picsum.photos/seed/2/200/300" />
            <img src="https://picsum.photos/seed/3/200/300" />
        </Flicking>}
      </div>
    );
  }
}

// packages/vue-flicking/demo/features/Image.vue
<template>
  <div class="container">
    <button @click="onClick">Click me</button>
    <flicking class="flicking" v-if="show" :options="flickingOptions">
      <img src="https://picsum.photos/seed/1/200/300" />
      <img src="https://picsum.photos/seed/2/200/300" />
      <img src="https://picsum.photos/seed/3/200/300" />
    </flicking>
  </div>
</template>
<script lang="ts">
import { Component, Vue } from "vue-property-decorator";

@Component({})
export default class ImageLoadDemo extends Vue {
  show = false;
  flickingOptions = {
    circular: true,
    duration: 300,
    resizeOnContentsReady: true,
  }

  onClick() {
    this.show = true;
  }
}
</script>
