// packages/ngx-flicking/projects/demo/src/app/image/image.component.ts
import { Component, OnInit } from '@angular/core';
import { ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'demo-image',
  templateUrl: './image.component.html',
  styleUrls: ['../app.component.css', './image.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ImageComponent implements OnInit {
  show = false;

  constructor() { }

  ngOnInit() {
  }

  onClick() {
    this.show = true;
  }
}

<div id="image" class="container">
  <button (click)="onClick()">Click me</button>
  <ngx-flicking *ngIf="show" class="flicking flicking0" [options]="{ circular: true, duration: 300, resizeOnContentsReady: true }">
    <ng-template>
      <img src="https://picsum.photos/seed/1/200/300" />
      <img src="https://picsum.photos/seed/2/200/300" />
      <img src="https://picsum.photos/seed/3/200/300" />
    </ng-template>
  </ngx-flicking>
</div>

// packages/vue-flicking/demo/features/Image.vue
<template>
  <div class="container">
    <button @click="onClick">Click me</button>
    <flicking class="flicking" v-if="show" :options="flickingOptions">
      <img src="https://picsum.photos/seed/1/200/300" />
      <img src="https://picsum.photos/seed/2/200/300" />
      <img src="https://picsum.photos/seed/3/200/300" />
    </flicking>
  </div>
</template>
<script lang="ts">
import { Component, Vue } from "vue-property-decorator";

@Component({})
export default class ImageLoadDemo extends Vue {
  show = false;
  flickingOptions = {
    circular: true,
    duration: 300,
    resizeOnContentsReady: true,
  }

  onClick() {
    this.show = true;
  }
}
</script>
