// packages/react-flicking/src/demo/features/Progress.tsx
import * as React from "react";
import Flicking from "../../react-flicking/Flicking";
import { insertCode } from "../utils";
import "../css/progress.css";

export default class Progress extends React.Component<{}> {
  private thumb: HTMLElement;
  public render() {
    return (
      <div id="progress" className="container">
        <h1>e.progress</h1>
        <ul className="extra">
          <li>Indicates the overall progress of the Flicking.</li>
        </ul>
        <Flicking className="flicking flicking0"
          gap={10}
          circular={true}
          moveType={{type: "snap", count: 5}}
          onMove={e => {
            this.thumb.style.width = (e.progress * 100) + "%";
          }}>
          <div className="panel"></div>
          <div className="panel"></div>
          <div className="panel"></div>
          <div className="panel"></div>
          <div className="panel"></div>
        </Flicking>
        <div className="progress">
          <div className="thumb" ref={e => { this.thumb = e as HTMLElement; }}></div>
      </div>
      <pre><code className="hljs html" data-script="flicking0"></code></pre>
      <h1>panel.getProgress()</h1>
      <ul className="extra">
        <li>Indicates the progress of the relative index of each panel.</li>
      </ul>
      <Flicking className="flicking flicking1"
          gap={10}
          circular={true}
          moveType={{type: "snap", count: 5}}
          onMove={e => {
            const flicking = e.currentTarget;

            flicking.getAllPanels(true).forEach(panel => {
              panel.getElement().innerHTML = panel.getProgress().toFixed(2);
            });
          }}>
        <div className="panel"></div>
        <div className="panel"></div>
        <div className="panel"></div>
        <div className="panel"></div>
        <div className="panel"></div>
      </Flicking>
      <div className="pagination pagination1"></div>
      <pre><code className="hljs html" data-script="flicking1"></code></pre>

      <h1>panel.getOutsetProgress()</h1>
      <ul className="extra">
        <li>When panel is completely invisible, outsetProgress becomes -1 at left(up), 1 at right(down) direction, and 0 when panel's anchor and hanger is overlapped.</li>
      </ul>
      <Flicking className="flicking flicking2"
          gap={10}
          circular={true}
          moveType={{type: "snap", count: 5}}
          onMove={e => {
            const flicking = e.currentTarget;

            flicking.getAllPanels(true).forEach(panel => {
              panel.getElement().innerHTML = panel.getOutsetProgress().toFixed(2);
            });
          }}>
        <div className="panel"></div>
        <div className="panel"></div>
        <div className="panel"></div>
        <div className="panel"></div>
        <div className="panel"></div>
      </Flicking>
      <div className="pagination pagination2"></div>
      <pre><code className="hljs html" data-script="flicking2"></code></pre>

      <h1>panel.getVisibleRatio()</h1>
      <ul className="extra">
        <li>Indicates the percentage of areas within the viewport that the panel occupies.</li>
      </ul>
      <Flicking className="flicking flicking3"
          gap={10}
          circular={true}
          moveType={{type: "snap", count: 5}}
          onMove={e => {
            const flicking = e.currentTarget;

            flicking.getAllPanels(true).forEach(panel => {
              panel.getElement().innerHTML = panel.getVisibleRatio().toFixed(2);
            });
          }}>
        <div className="panel"></div>
        <div className="panel"></div>
        <div className="panel"></div>
        <div className="panel"></div>
        <div className="panel"></div>
      </Flicking>
      <div className="pagination pagination3"></div>
      <pre><code className="hljs html" data-script="flicking3"></code></pre>
</div >);
  }
  public componentDidMount() {
    insertCode("progress", 0, `
  <Flicking className="flicking flicking0"
    gap={10}
    circular={true}
    moveType={{type: "snap", count: 5}}
    onMove={e => {
      this.thumb.style.width = (e.progress * 100) + "%";
    }}>
    <div className="panel"></div>
    <div className="panel"></div>
    <div className="panel"></div>
    <div className="panel"></div>
    <div className="panel"></div>
  </Flicking>`);
    insertCode("progress", 1, `
<Flicking className="flicking flicking1"
  gap={10}
  circular={true}
  moveType={{type: "snap", count: 5}}
  onMove={e => {
    const flicking = e.currentTarget;

    flicking.getAllPanels(true).forEach(panel => {
      panel.getElement().innerHTML = panel.getProgress().toFixed(2);
    });
  }}>
  <div className="panel"></div>
  <div className="panel"></div>
  <div className="panel"></div>
  <div className="panel"></div>
  <div className="panel"></div>
</Flicking>`);
    insertCode("progress", 2, `
  <Flicking className="flicking flicking2"
    gap={10}
    circular={true}
    moveType={{type: "snap", count: 5}}
    onMove={e => {
      const flicking = e.currentTarget;

      flicking.getAllPanels(true).forEach(panel => {
        panel.getElement().innerHTML = panel.getOutsetProgress().toFixed(2);
      });
    }}>
    <div className="panel"></div>
    <div className="panel"></div>
    <div className="panel"></div>
    <div className="panel"></div>
    <div className="panel"></div>
  </Flicking>`);
    insertCode("progress", 3, `
  <Flicking className="flicking flicking3"
    gap={10}
    circular={true}
    moveType={{type: "snap", count: 5}}
    onMove={e => {
      const flicking = e.currentTarget;

      flicking.getAllPanels(true).forEach(panel => {
        panel.getElement().innerHTML = panel.getVisibleRatio().toFixed(2);
      });
    }}>
    <div className="panel"></div>
    <div className="panel"></div>
    <div className="panel"></div>
    <div className="panel"></div>
    <div className="panel"></div>
  </Flicking>`);
  }
}

// packages/vue-flicking/demo/features/Progress.vue
<template>
  <div id="progress" class="container" v-highlight>
    <h1>e.progress</h1>
    <ul class="extra">
      <li>Indicates the overall progress of the flicking.</li>
    </ul>
    <flicking class="flicking flicking0"
      :options="{
        gap: 10,
        circular: true,
        moveType: { type: 'snap', count: 5 },
      }"
      @move="e => {
        this.$refs.thumb.style.width = (e.progress * 100) + '%';
      }">
      <div class="panel"></div>
      <div class="panel"></div>
      <div class="panel"></div>
      <div class="panel"></div>
      <div class="panel"></div>
    </flicking>
    <div class="progress">
      <div class="thumb" ref="thumb"></div>
    </div>
    <pre><code class="hljs html" data-script="flicking0">{{ code0 }}</code></pre>
    <h1>panel.getProgress()</h1>
    <ul class="extra">
    <li>Indicates the progress of the relative index of each panel.</li>
    </ul>
    <flicking class="flicking flicking1"
      :option="{
        gap: 10,
        circular: true,
        moveType: { type: 'snap', count: 5 },
      }"
      @move="e => {
        e.currentTarget.getAllPanels(true).forEach(panel => {
          panel.getElement().innerHTML = panel.getProgress().toFixed(2);
        });
      }"
      ref="flicking1">
      <div class="panel"></div>
      <div class="panel"></div>
      <div class="panel"></div>
      <div class="panel"></div>
      <div class="panel"></div>
    </flicking>
    <div class="pagination pagination1"></div>
    <pre><code class="hljs html" data-script="flicking1">{{ code1 }}</code></pre>

    <h1>panel.getOutsetProgress()</h1>
    <ul class="extra">
    <li>When panel is completely invisible, outsetProgress becomes -1 at left(up), 1 at right(down) direction, and 0 when panel's anchor and hanger is overlapped.</li>
    </ul>
    <flicking class="flicking flicking2"
      :options="{
        gap: 10,
        circular: true,
        moveType: { type: 'snap', count: 5 }
      }"
      @move="e => {
        const flicking = e.currentTarget;

        flicking.getAllPanels(true).forEach(panel => {
          panel.getElement().innerHTML = panel.getOutsetProgress().toFixed(2);
        });
      }">
      <div class="panel"></div>
      <div class="panel"></div>
      <div class="panel"></div>
      <div class="panel"></div>
      <div class="panel"></div>
    </flicking>
    <div class="pagination pagination2"></div>
    <pre><code class="hljs html" data-script="flicking2">{{ code2 }}</code></pre>

    <h1>panel.getVisibleRatio()</h1>
    <ul class="extra">
    <li>Indicates the percentage of areas within the viewport that the panel occupies.</li>
    </ul>
    <flicking class="flicking flicking3"
      :options="{
        gap: 10,
        circular: true,
        moveType: { type: 'snap', count: 5}
      }"
      @move="e => {
        const flicking = e.currentTarget;

        flicking.getAllPanels(true).forEach(panel => {
          panel.getElement().innerHTML = panel.getVisibleRatio().toFixed(2);
        });
      }">
      <div class="panel"></div>
      <div class="panel"></div>
      <div class="panel"></div>
      <div class="panel"></div>
      <div class="panel"></div>
    </flicking>
    <div class="pagination pagination3"></div>
    <pre><code class="hljs html" data-script="flicking3">{{ code3 }}</code></pre>
  </div >
</template>
<script lang="ts">
import { Component, Vue } from "vue-property-decorator";

@Component({})
export default class Progress extends Vue {
  code0 = `<flicking class="flicking flicking0"
  :options="{
    gap: 10,
    circular: true,
    moveType: { type: 'snap', count: 5 },
  }"
  @move="e => {
    this.$refs.thumb.style.width = (e.progress * 100) + '%';
  }">
  <div class="panel"></div>
  <div class="panel"></div>
  <div class="panel"></div>
  <div class="panel"></div>
  <div class="panel"></div>
</flicking>`;
  code1 = `<flicking class="flicking flicking1"
  :option="{
    gap: 10,
    circular: true,
    moveType: { type: 'snap', count: 5 },
  }"
  @move="e => {
    e.currentTarget.getAllPanels(true).forEach(panel => {
      panel.getElement().innerHTML = panel.getProgress().toFixed(2);
    });
  }">
  <div class="panel"></div>
  <div class="panel"></div>
  <div class="panel"></div>
  <div class="panel"></div>
  <div class="panel"></div>
</flicking>`;
  code2 = `<flicking class="flicking flicking2"
  :options="{
    gap: 10,
    circular: true,
    moveType: { type: 'snap', count: 5 }
  }"
  @move="e => {
    const flicking = e.currentTarget;

    flicking.getAllPanels(true).forEach(panel => {
      panel.getElement().innerHTML = panel.getOutsetProgress().toFixed(2);
    });
  }">
  <div class="panel"></div>
  <div class="panel"></div>
  <div class="panel"></div>
  <div class="panel"></div>
  <div class="panel"></div>
</flicking>`;
  code3 = `<flicking class="flicking flicking3"
  :options="{
    gap: 10,
    circular: true,
    moveType: { type: 'snap', count: 5}
  }"
  @move="e => {
    const flicking = e.currentTarget;

    flicking.getAllPanels(true).forEach(panel => {
      panel.getElement().innerHTML = panel.getVisibleRatio().toFixed(2);
    });
  }">
  <div class="panel"></div>
  <div class="panel"></div>
  <div class="panel"></div>
  <div class="panel"></div>
  <div class="panel"></div>
</flicking>`;
}
</script>
<style scoped>
  #progress .progress {
    position: relative;
    width: 400px;
    height: 10px;
    border-radius: 5px;
    background: #eee;
    margin: 10px auto;
    overflow: hidden;
  }
  #progress .thumb {
    position: relative;
    height: 100%;
    width: 0;
    border-radius: inherit;
    background: #ccc;
  }
</style>
