// packages/ngx-flicking/projects/demo/src/app/virtual/virtual.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "demo-virtual",
  templateUrl: "./virtual.component.html",
  styleUrls: ["../app.component.css", "./virtual.component.css"]
})
export class VirtualComponent {
  public flickingOptions = {
    panelsPerView: 5,
    circular: true,
    virtual: {
      cache: true,
      panelClass: "panel",
      renderPanel: (panel) => `<span>Panel ${panel.index}</span>`,
      initialPanelCount: 100
    }
  };
}

<div id="variable-size" class="container">
  <ngx-flicking class="flicking flicking0"
  [options]="flickingOptions" #flick></ngx-flicking>
  <div class="buttons">
    <button id="prepend" (click)="flick.virtual.prepend(100)">Prepend</button>
    <button id="append" (click)="flick.virtual.append(100)">Append</button>
  </div>
</div>

// packages/vue-flicking/demo/features/Virtual.vue
<template>
  <div class="container">
    <flicking class="flicking flicking0" ref="flicking" :options="{
      panelsPerView: 5,
      circular: true,
      virtual: {
        cache: true,
        panelClass: 'panel',
        renderPanel: (panel) => `<span>Panel ${panel.index}</span>`,
        initialPanelCount: 100
      }
    }"></flicking>
    <button @click="this.prepend">Prepend</button>
    <button @click="this.append">Append</button>
  </div>
</template>
<script lang="ts">
import { Component, Vue } from "vue-property-decorator";

@Component({})
export default class VariableSize extends Vue {
  public prepend() {
    (this.$refs.flicking as any).virtual.prepend(100);
  }

  public append() {
    (this.$refs.flicking as any).virtual.append(100);
  }
}
</script>
