// packages/react-flicking/src/demo/App.tsx

import React, { Component } from "react";
import {
  BrowserRouter as Router,
  Routes,
  Route
} from "react-router-dom";
import "./css/common.css";
import "./css/features.css";
import "./css/highlight.css";
import "@egjs/flicking/dist/flicking.css";
import "@egjs/flicking-plugins/dist/flicking-plugins.css";
import hljs from "highlight.js";
import InfiniteFlicking from "./features/InfiniteFlicking";
import FreeScroll from "./features/FreeScroll";
import VariableSize from "./features/VariableSize";
import Align from "./features/Align";
import Snap from "./features/Snap";
import Progress from "./features/Progress";
import Bound from "./features/Bound";
import Virtual from "./features/Virtual";
import PropChange from "./features/PropChange";
import Parallax from "./plugins/Parallax";
import Fade from "./plugins/Fade";
import AutoPlay from "./plugins/AutoPlay";
import Arrow from "./plugins/Arrow";
import Header from "./Header";

export default class App extends Component<{}> {
  public render() {
    return (
      <Router>
        <Header/>
        <Routes>
          <Route path="/infinite" element={<InfiniteFlicking />} />
          <Route path="/free-scroll" element={<FreeScroll />} />
          <Route path="/variable-size" element={<VariableSize />} />
          <Route path="/align" element={<Align />} />
          <Route path="/snap" element={<Snap />} />
          <Route path="/progress" element={<Progress />} />
          <Route path="/bound" element={<Bound />} />
          <Route path="/virtual" element={<Virtual />} />
          <Route path="/parallax" element={<Parallax />} />
          <Route path="/fade" element={<Fade />} />
          <Route path="/autoplay" element={<AutoPlay />} />
          <Route path="/arrow" element={<Arrow />} />
          <Route path="/prop" element={<PropChange />} />
        </Routes>
      </Router>);
  }
  public componentDidMount() {
    hljs.initHighlighting();
  }
}

// packages/ngx-flicking/projects/demo/src/app/app.component.ts
import { Component, ElementRef } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  constructor(private elRef: ElementRef) {
  }
}

<!-- <demo-custom></demo-custom> -->
<nav>
  <a routerLink="/align" routerLinkActive="active">Align</a>
  <a routerLink="/bound" routerLinkActive="active">Bound</a>
  <a routerLink="/freescroll" routerLinkActive="active">FreeScroll</a>
  <a routerLink="/gap" routerLinkActive="active">Gap</a>
  <a routerLink="/infinite" routerLinkActive="active">Infinite</a>
  <a routerLink="/progress" routerLinkActive="active">Progress</a>
  <a routerLink="/snap" routerLinkActive="active">Snap</a>
  <a routerLink="/variable-size" routerLinkActive="active">Variable Size</a>
  <a routerLink="/virtual" routerLinkActive="active">Virtual</a>
  <a routerLink="/prop" routerLinkActive="active">PropChange</a>
  <a routerLink="/autoplay" routerLinkActive="active">Auto Play</a>
  <a routerLink="/fade" routerLinkActive="active">Fade</a>
  <a routerLink="/parallax" routerLinkActive="active">Parallax</a>
  <a routerLink="/custom" routerLinkActive="active">Custom</a>
  <a routerLink="/visiblepanels" routerLinkActive="active">Render Only Visible</a>
  <a routerLink="/arrow" routerLinkActive="active">Arrow</a>
  <a routerLink="/sync" routerLinkActive="active">Sync</a>
</nav>
<router-outlet></router-outlet>
