// packages/ngx-flicking/projects/demo/src/app/gap/gap.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'demo-gap',
  templateUrl: './gap.component.html',
  styleUrls: ['../app.component.css', './gap.component.css']
})
export class GapComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div id="gap" class="container" v-highlight>
  <h1>Gap</h1>
  <ul class="extra">
    <li>You can specify the interval between the frames.</li>
  </ul>
  <h2>Default</h2>
  <ngx-flicking class="flicking flicking0" [options]="{ bound: true }">
    <ng-template>
      <div class="panel"></div>
      <div class="panel"></div>
      <div class="panel"></div>
      <div class="panel"></div>
      <div class="panel"></div>
      <div class="panel"></div>
    </ng-template>
  </ngx-flicking>
  <div class="pagination pagination0"></div>
  <pre><code class="hljs html" data-script="flicking0">{{ code0 }}</code></pre>
  <h2>gap: 20</h2>
  <ngx-flicking class="flicking flicking1" [options]="{ gap: 20, bound: true }">
    <ng-template>
      <div class="panel"></div>
      <div class="panel"></div>
      <div class="panel"></div>
      <div class="panel"></div>
      <div class="panel"></div>
      <div class="panel"></div>
    </ng-template>
  </ngx-flicking>
  <div class="pagination pagination1"></div>
  <pre><code class="hljs html" data-script="flicking1">{{ code1 }}</code></pre>
</div>

// packages/preact-flicking/src/demo/features/Gap.tsx
import { h, Component } from "preact";
import Flicking from "../../preact-flicking";
import { insertCode } from "../utils";
import "../css/gap.css";

export default class Gap extends Component<{}> {
  public render() {
    return (
      <div id="gap" className="container">
        <h1>Gap</h1>
        <ul className="extra">
          <li>You can specify the interval between the frames.</li>
        </ul>
        <h2>Default</h2>
        <Flicking className="flicking flicking0" bound={true}>
          <div className="panel"></div>
          <div className="panel"></div>
          <div className="panel"></div>
          <div className="panel"></div>
          <div className="panel"></div>
          <div className="panel"></div>
        </Flicking>
        <div className="pagination pagination0"></div>
        <pre><code className="hljs html" data-script="flicking0"></code></pre>
        <h2>gap: 20</h2>
        <Flicking className="flicking flicking1" gap={20} bound={true}>
          <div className="panel"></div>
          <div className="panel"></div>
          <div className="panel"></div>
          <div className="panel"></div>
          <div className="panel"></div>
          <div className="panel"></div>
        </Flicking>
        <div className="pagination pagination1"></div>
        <pre><code className="hljs html" data-script="flicking1"></code></pre>
      </div>);
  }
  public componentDidMount() {
    insertCode("gap", 0, `
  <Flicking className="flicking flicking0" bound={true}>
    <div className="panel"></div>
    <div className="panel"></div>
    <div className="panel"></div>
    <div className="panel"></div>
    <div className="panel"></div>
    <div className="panel"></div>
  </Flicking>`);
    insertCode("gap", 1, `
  <Flicking className="flicking flicking1" gap={20} bound={true}>
    <div className="panel"></div>
    <div className="panel"></div>
    <div className="panel"></div>
    <div className="panel"></div>
    <div className="panel"></div>
    <div className="panel"></div>
  </Flicking>`);
  }
}
