// packages/vue-flicking/demo/ssr/pages/features/component/PlaceHolderItem.vue
<template>
  <div class="infinite" :class="classes"></div>
</template>
<script>
export default {
  data() {
    return {
      loaded: false,
    }
  },
  computed: {
    classes() {
      return `panel${this.$props.num % 5} ${this.loaded ? "" : "placeholder"}`;
    }
  },
  props: {
    num: Number
  },
  mounted() {
        setTimeout(() => {
      this.loaded = true;
    }, 1500);
  }
}
</script>

// packages/preact-flicking/src/demo/features/PlaceHolderItem.tsx
import { h, Component } from "preact";

export default class PlaceHolderItem extends Component<{num: number}, {loaded: boolean}> {
  public state = {
    loaded: false,
  };
  public render() {
    const num = this.props.num;
    const loaded = this.state.loaded;
    return <div className={`infinite infinite${Math.abs(num) % 5} ${loaded ? "" : "placeholder"}`}>{num}</div>;
  }
  public componentDidMount() {
    setTimeout(() => {
      this.setState({loaded: true});
    }, 1500);
  }
}
