// packages/vue-flicking/demo/features/Virtual.vue
<template>
  <div class="container">
    <flicking class="flicking flicking0" ref="flicking" :options="{
      panelsPerView: 5,
      circular: true,
      virtual: {
        cache: true,
        panelClass: 'panel',
        renderPanel: (panel) => `<span>Panel ${panel.index}</span>`,
        initialPanelCount: 100
      }
    }"></flicking>
    <button @click="this.prepend">Prepend</button>
    <button @click="this.append">Append</button>
  </div>
</template>
<script lang="ts">
import { Component, Vue } from "vue-property-decorator";

@Component({})
export default class VariableSize extends Vue {
  public prepend() {
    (this.$refs.flicking as any).virtual.prepend(100);
  }

  public append() {
    (this.$refs.flicking as any).virtual.append(100);
  }
}
</script>

// packages/react-flicking/dev/archive/features/Virtual.tsx
import Flicking from "@dev/react-flicking";
import * as React from "react";

// eslint-disable-next-line import/no-anonymous-default-export
export default () => {
  const [num, setNum] = React.useState(1);
  const flicking = React.useRef<Flicking>();
  const virtual = React.useMemo(
    () => ({
      cache: true,
      panelClass: "panel",
      renderPanel: panel => `<span>Panel ${panel.index}</span>`,
      initialPanelCount: 100
    }),
    []
  );

  return (
    <div className="container">
      <h1>virtual</h1>
      <button onClick={() => setNum(num + 1)}>{num}</button>
      <Flicking
        ref={flicking as any}
        className="flicking flicking0"
        panelsPerView={5}
        circular={true}
        virtual={virtual}
      />
      <button
        onClick={() => {
          flicking.current?.virtual.prepend(100);
        }}
      >
        PREPEND
      </button>
      <button
        onClick={() => {
          flicking.current?.virtual.append(100);
        }}
      >
        APPEND
      </button>
    </div>
  );
};
