// packages/vue3-flicking/demo/App.vue
<template>
  <article>
    <div class="container">
      <h1>Default Rendering</h1>
      <Flicking>
        <div class="panel">0</div>
        <div class="panel">1</div>
        <div class="panel">2</div>
      </Flicking>
      <h1>Bound</h1>
      <Flicking :options="{ bound: true }">
        <div class="panel">0</div>
        <div class="panel">1</div>
        <div class="panel">2</div>
        <div class="panel">3</div>
        <div class="panel">4</div>
        <div class="panel">5</div>
        <div class="panel">6</div>
      </Flicking>
      <h1>FreeScroll</h1>
      <Flicking :options="{ moveType: 'freeScroll' }">
        <div class="panel">0</div>
        <div class="panel">1</div>
        <div class="panel">2</div>
      </Flicking>
      <h1>List Rendering</h1>
      <Flicking>
        <Test v-for="item in list0" :key="item" />
      </Flicking>
      <h1>Adding panels</h1>
      <Flicking :options="{ circular: true, renderOnlyVisible: true }">
        <div class="panel" v-for="panel in panels" :key="panel">{{ panel }}</div>
        <Test />
      </Flicking>
      <div>
        <span class="button" @click="() => {
          prepend();
        }">Prepend</span>
        <span class="button" @click="() => {
          append();
        }">Append</span>
      </div>
      <h1>Method call</h1>
      <Flicking ref="flick" :options="{ circular: true }">
        <div class="panel">0</div>
        <div class="panel">1</div>
        <div class="panel">2</div>
        <div class="panel">3</div>
        <div class="panel">4</div>
        <div class="panel">5</div>
        <div class="panel">6</div>
        <div class="panel">7</div>
        <div class="panel">8</div>
      </Flicking>
      <div>
        <span class="button" @click="() => {
          prev();
        }">Prev</span>
        <span class="button" @click="() => {
          next();
        }">Next</span>
      </div>
      <Flicking :plugins="arrow">
        <div class="panel">0</div>
        <div class="panel">1</div>
        <div class="panel">2</div>
        <div class="panel">3</div>
        <div class="panel">4</div>
        <template #viewport>
          <span class="flicking-arrow-prev"></span>
          <span class="flicking-arrow-next"></span>
        </template>
      </Flicking>
      <Flicking :plugins="arrow">
        <div class="panel">0</div>
        <div class="panel">1</div>
        <div class="panel">2</div>
        <div class="panel">3</div>
        <div class="panel">4</div>
        <template #viewport>
          <span class="flicking-arrow-prev"></span>
          <span class="flicking-arrow-next"></span>
        </template>
      </Flicking>
      <Flicking class="flicking flicking0" ref="vFlick" :options="{
        panelsPerView: 5,
        circular: true,
        virtual: {
          panelClass: 'panel',
          renderPanel: (panel) => `Panel ${panel.index}`,
          initialPanelCount: 100
        }
      }"></Flicking>
      <button @click="this.vPrepend">Prepend</button>
      <button @click="this.vAppend">Append</button>
    </div>
  </article>
</template>

<script>
import Flicking from "../src/Flicking";
import Test from "./components/Test.vue";
import Test2 from "./components/Test2.vue";
import { Arrow } from "@egjs/flicking-plugins";

export default {
  components: {
    Flicking,
    Test,
    Test2
  },
  data() {
    return {
      panels: [0, 1, 2, 3, 4, 5, 6],
      list0: [0, 1, 2],
      arrow: [new Arrow()]
    }
  },
  methods: {
    prepend() {
      this.panels.splice(0, 0, this.panels[0] - 2, this.panels[0] - 1)
    },
    append() {
      const lastEl = this.panels[this.panels.length - 1];
      this.panels.push(lastEl + 1, lastEl + 2)
    },
    prev() {
      this.$refs.flick.prev();
    },
    next() {
      this.$refs.flick.next();
    },
    vPrepend() {
      this.$refs.vFlick.virtual.prepend(100);
    },
    vAppend() {
      this.$refs.vFlick.virtual.append(100);
    }
  }
}
</script>

<style>


#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}

.panel {
  width: 200px;
  height: 200px;
  margin-right: 20px;
  display: inline-flex;
  justify-content: center;
  align-items: center;
}
</style>

// packages/svelte-flicking/demo/App.svelte
<script lang="ts">
  import { Arrow } from "@egjs/flicking-plugins";
  import Flicking from "../src/Flicking";
  import { FlickingPanel } from "../src";
  import "@egjs/flicking/dist/flicking.css";
  import "@egjs/flicking-plugins/dist/flicking-plugins.css";
  import Test from "./Test.svelte";

  let flick: Flicking;
  let vFlick: Flicking;
  let panels = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
  let list0 = [0, 1, 2];
  const plugins = [new Arrow()];

  function prepend() {
    panels = [panels[0] - 2, panels[0] - 1, ...panels];
  }

  function append() {
    const lastEl = panels[panels.length - 1];
    panels = [...panels, lastEl + 1, lastEl + 2];
  }

  function prev() {
    flick.prev();
  }

  function next() {
    flick.next();
  }

  function vPrepend() {
    vFlick.virtual.prepend(100);
  }

  function vAppend() {
    vFlick.virtual.append(100);
  }
</script>

<div class="container">
  <h1>Default Rendering</h1>
  <Flicking hideBeforeInit={true}>
    <FlickingPanel><div class="panel">0</div></FlickingPanel>
    <FlickingPanel><div class="panel">1</div></FlickingPanel>
    <FlickingPanel><div class="panel">2</div></FlickingPanel>
  </Flicking>
  <h1>Bound</h1>
  <Flicking options={{ bound: true }}>
    <FlickingPanel><div class="panel">0</div></FlickingPanel>
    <FlickingPanel><div class="panel">1</div></FlickingPanel>
    <FlickingPanel><div class="panel">2</div></FlickingPanel>
    <FlickingPanel><div class="panel">3</div></FlickingPanel>
    <FlickingPanel><div class="panel">4</div></FlickingPanel>
    <FlickingPanel><div class="panel">5</div></FlickingPanel>
    <FlickingPanel><div class="panel">6</div></FlickingPanel>
  </Flicking>
  <h1>FreeScroll</h1>
  <Flicking options={{ moveType: "freeScroll", align: "center" }} firstPanelSize={"200px"}>
    <FlickingPanel><div class="panel">0</div></FlickingPanel>
    <FlickingPanel><div class="panel">1</div></FlickingPanel>
    <FlickingPanel><div class="panel">2</div></FlickingPanel>
  </Flicking>
  <h1>List Rendering</h1>
  <Flicking>
    {#each list0 as item}
      <FlickingPanel><Test /></FlickingPanel>
    {/each}
  </Flicking>
  <h1>Adding panels</h1>
  <Flicking options={{ circular: true, renderOnlyVisible: true }}>
    {#each panels as panel, idx (panel)}
      <FlickingPanel><div class={`panel panel${panel % 5}`}>{ panel }</div></FlickingPanel>
    {/each}
  </Flicking>
  <div>
    <span class="button" on:click={prepend}>Prepend</span>
    <span class="button" on:click={() => {
      append();
    }}>Append</span>
  </div>
  <h1>Method call</h1>
  <Flicking bind:this={flick}>
    <FlickingPanel><div class="panel">0</div></FlickingPanel>
    <FlickingPanel><div class="panel">1</div></FlickingPanel>
    <FlickingPanel><div class="panel">2</div></FlickingPanel>
  </Flicking>
  <div>
    <span class="button" on:click={() => {
      prev();
    }}>Prev</span>
    <span class="button" on:click={() => {
      next();
    }}>Next</span>
  </div>
  <Flicking plugins={plugins}>
    <FlickingPanel><div class="panel">0</div></FlickingPanel>
    <FlickingPanel><div class="panel">1</div></FlickingPanel>
    <FlickingPanel><div class="panel">2</div></FlickingPanel>
    <FlickingPanel><div class="panel">3</div></FlickingPanel>
    <FlickingPanel><div class="panel">4</div></FlickingPanel>
    <div slot="viewport">
      <span class="flicking-arrow-prev"></span>
      <span class="flicking-arrow-next"></span>
    </div>
  </Flicking>
  <h1>Virtual</h1>
  <Flicking bind:this={vFlick} options={{
    panelsPerView: 5,
    circular: true,
    virtual: {
      cache: true,
      panelClass: 'panel',
      renderPanel: (panel) => `<span>Panel ${panel.index}</span>`,
      initialPanelCount: 100
    }
  }} />
  <div>
    <span class="button" on:click={() => {
      vPrepend();
    }}>Prepend</span>
    <span class="button" on:click={() => {
      vAppend();
    }}>Append</span>
  </div>
</div>

<style>
  :global(.panel) {
    display: flex;
    width: 200px;
    height: 200px;
    justify-content: center;
    align-items: center;
    margin-right: 20px;
  }

  :global(.panel0) {
    background-color: red;
  }
  :global(.panel1) {
    background-color: blue;
  }
  :global(.panel2) {
    background-color: green;
  }
  :global(.panel3) {
    background-color: violet;
  }
</style>
