// packages/vue-flicking/demo/plugins/Arrow.vue
<template>
<div id="arrow" class="container">
  <flicking class="flicking flicking0" :plugins="plugins">
    <div class="panel0"><div class="anchor"></div></div>
    <div class="panel1"><div class="anchor"></div></div>
    <div class="panel2"><div class="anchor"></div></div>
    <div class="panel3"><div class="anchor"></div></div>
    <div class="panel4"><div class="anchor"></div></div>
    <span slot="viewport" class="flicking-arrow-prev"></span>
    <span slot="viewport" class="flicking-arrow-next"></span>
  </flicking>
</div>
</template>
<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { Arrow } from "@egjs/flicking-plugins";

@Component({})
export default class ArrowDemo extends Vue {
  plugins = [new Arrow()];
}
</script>
<style scoped>

</style>

// packages/react-flicking/src/demo/plugins/Arrow.tsx
import * as React from "react";
import Flicking from "../../react-flicking/Flicking";
import { Arrow } from "@egjs/flicking-plugins";
import "../css/plugins.css";

export default class ArrowDemo extends React.Component<{}> {
  private plugins = [new Arrow()];
  public render() {
    return (
    <div id="arrow" className="container">
      <Flicking
        className="flicking"
        circular={true}
        gap={10}
        duration={500}
        plugins={this.plugins}
      >
        <div className="panel panel0"></div>
        <div className="panel panel1"></div>
        <div className="panel panel2"></div>
        <div className="panel panel3"></div>
        <div className="panel panel4"></div>
        <span slot="viewport" className="flicking-arrow-prev"></span>
        <span slot="viewport" className="flicking-arrow-next"></span>
      </Flicking>
  </div>);
  }
}
