// packages/ngx-flicking/projects/demo/src/app/arrow/arrow.component.ts
import { Component, OnInit } from "@angular/core";
import { Arrow } from "@egjs/flicking-plugins";

@Component({
  selector: "demo-arrow",
  templateUrl: "./arrow.component.html",
  styleUrls: ["../app.component.css", "./arrow.component.css", "../../../../../node_modules/@egjs/flicking-plugins/dist/flicking-plugins.css"]
})
export class ArrowComponent implements OnInit {
  plugins: any[] = [new Arrow()];

  constructor() { }

  ngOnInit() {
  }
}

<div id="arrow" class="container">
  <ngx-flicking
    class="flicking"
    [options]="{ circular: true, gap: 10, duration: 500 }"
    [plugins]="plugins"
  >
    <div flicking-panel class="panel panel0"></div>
    <div flicking-panel class="panel panel1"></div>
    <div flicking-panel class="panel panel2"></div>
    <div flicking-panel class="panel panel3"></div>
    <div flicking-panel class="panel panel4"></div>
    <span in-viewport class="flicking-arrow-prev"></span>
    <span in-viewport class="flicking-arrow-next"></span>
  </ngx-flicking>
</div>

// packages/react-flicking/src/demo/plugins/Arrow.tsx
import * as React from "react";
import Flicking from "../../react-flicking/Flicking";
import { Arrow } from "@egjs/flicking-plugins";
import "../css/plugins.css";

export default class ArrowDemo extends React.Component<{}> {
  private plugins = [new Arrow()];
  public render() {
    return (
    <div id="arrow" className="container">
      <Flicking
        className="flicking"
        circular={true}
        gap={10}
        duration={500}
        plugins={this.plugins}
      >
        <div className="panel panel0"></div>
        <div className="panel panel1"></div>
        <div className="panel panel2"></div>
        <div className="panel panel3"></div>
        <div className="panel panel4"></div>
        <span slot="viewport" className="flicking-arrow-prev"></span>
        <span slot="viewport" className="flicking-arrow-next"></span>
      </Flicking>
  </div>);
  }
}
