// packages/vue-flicking/demo/plugins/Parallax.vue
<template>
  <div id="parallax" class="plugins container">
    <h1>Parallax <a
      href="https://naver.github.io/egjs-flicking-plugins/release/latest/doc/eg.flicking.plugins.Parallax.html"
      target="_blank">API</a></h1>
    <ul class="extra">
      <li>Parallax effect will be applied to each panel while moving.</li>
    </ul>
    <flicking class="flicking"
      :options="{ gap: 10, circular: true }"
      :plugins="plugins"
    >
      <div class="panel">
        <img src="https://naver.github.io/egjs-flicking/images/bg01.jpg" />
      </div>
      <div class="panel">
        <img src="https://naver.github.io/egjs-flicking/images/bg02.jpg" />
      </div>
      <div class="panel">
        <img src="https://naver.github.io/egjs-flicking/images/bg03.jpg" />
      </div>
    </flicking>
    <div class="pagination"></div>
    <pre><code class="hljs html" data-script="flicking0">{{ code0 }}</code></pre>
  </div>
</template>
<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { Parallax } from "@egjs/flicking-plugins";

@Component({})
export default class AutoPlayDemo extends Vue {
  public mounted() {
    document.querySelectorAll('.hljs').forEach((block) => {
      (window as any).hljs.highlightBlock(block);
    });
  }

  plugins = [new Parallax("img", 4)];
  code0 = `<!--
  import { Parallax } from "@egjs/flicking-plugins";
  plugins = [new Parallax("img", 4)];
-->
<flicking class="flicking"
  :options="{ gap: 10, circular: true }"
  :plugins="plugins"
>
  <div class="panel">
    <img src="https://naver.github.io/egjs-flicking/images/bg01.jpg" />
  </div>
  <div class="panel">
    <img src="https://naver.github.io/egjs-flicking/images/bg02.jpg" />
  </div>
  <div class="panel">
    <img src="https://naver.github.io/egjs-flicking/images/bg03.jpg" />
  </div>
</flicking>`;
}
</script>
<style scoped>
#parallax .flicking .panel {
  width: 500px;
}
</style>

// packages/react-flicking/src/demo/plugins/Parallax.tsx
import * as React from "react";
import Flicking from "../../react-flicking/Flicking";
import { insertCode } from "../utils";
import { Parallax } from "@egjs/flicking-plugins";
import "../css/plugins.css";
import "../css/parallax.css";

export default class ParallaxDemo extends React.Component<{}> {
  private plugins = [new Parallax("img", 4)];
  public render() {
    return (
      <div id="parallax" className="plugins container">
        <h1>Parallax <a
          href="https://naver.github.io/egjs-flicking-plugins/release/latest/doc/eg.Flicking.plugins.Parallax.html"
          target="_blank">API</a></h1>
        <ul className="extra">
          <li>Parallax effect will be applied to each panel while moving.</li>
        </ul>
        <Flicking
          className="flicking"
          gap={10}
          circular={true}
          plugins={this.plugins}
        >
          <div className="panel">
            <img src="https://naver.github.io/egjs-flicking/images/bg01.jpg" />
          </div>
          <div className="panel">
            <img src="https://naver.github.io/egjs-flicking/images/bg02.jpg" />
          </div>
          <div className="panel">
            <img src="https://naver.github.io/egjs-flicking/images/bg03.jpg" />
          </div>
        </Flicking>
        <div className="pagination"></div>
        <pre><code className="hljs html" data-script="flicking0"></code></pre>
      </div>);
  }
  public componentDidMount() {
    insertCode("parallax", 0, `
import { Parallax } from "@egjs/flicking-plugins";
this.plugins = [new Parallax("img", 4)];

<Flicking
  className="flicking"
  gap={10}
  circular={true}
  plugins={this.plugins}
>
  <div className="panel">
    <img src="https://naver.github.io/egjs-flicking/images/bg01.jpg" />
  </div>
  <div className="panel">
    <img src="https://naver.github.io/egjs-flicking/images/bg02.jpg" />
  </div>
  <div className="panel">
    <img src="https://naver.github.io/egjs-flicking/images/bg03.jpg" />
  </div>
</Flicking>`);
  }
}
