// packages/preact-flicking/src/demo/features/Bound.tsx
import { h, Component } from "preact";
import Flicking from "../../preact-flicking";
import { insertCode } from "../utils";
import "../css/bound.css";

export default class Bound extends Component<{}> {
  public render() {
    return (
      <div id="bound" className="container">
        <h1>Bound <img src="https://naver.github.io/egjs-flicking/images/bound-dog.png" width="40px" /></h1>
        <ul className="extra">
          <li>Bound the panels so that they are not out of the flicking area.</li>
          <li>This prevents unwanted free space within the flicking area.</li>
        </ul>
        <h2>bound: false</h2>
        <div className="hanger hanger0"></div>
        <Flicking className="flicking flicking0" gap={10}>
          <div className="panel"><div className="anchor"></div></div>
          <div className="panel"><div className="anchor"></div></div>
          <div className="panel"><div className="anchor"></div></div>
          <div className="panel"><div className="anchor"></div></div>
          <div className="panel"><div className="anchor"></div></div>
          <div className="panel"><div className="anchor"></div></div>
        </Flicking>
        <h2>bound: true</h2>
        <div className="hanger hanger0"></div>
        <Flicking className="flicking flicking1" gap={10} bound={true}>
          <div className="panel"><div className="anchor"></div></div>
          <div className="panel"><div className="anchor"></div></div>
          <div className="panel"><div className="anchor"></div></div>
          <div className="panel"><div className="anchor"></div></div>
          <div className="panel"><div className="anchor"></div></div>
          <div className="panel"><div className="anchor"></div></div>
        </Flicking>
        <div className="pagination pagination2"></div>
        <pre><code className="hljs html" data-script="flicking1"></code></pre>
      </div>);
  }
  public componentDidMount() {
    insertCode("bound", 1, `
  <Flicking className="flicking flicking1" bound={true}>
    <div className="panel"><div className="anchor"></div></div>
    <div className="panel"><div className="anchor"></div></div>
    <div className="panel"><div className="anchor"></div></div>
    <div className="panel"><div className="anchor"></div></div>
    <div className="panel"><div className="anchor"></div></div>
    <div className="panel"><div className="anchor"></div></div>
  </Flicking>`);
  }
}

// packages/ngx-flicking/projects/demo/src/app/bound/bound.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'demo-bound',
  templateUrl: './bound.component.html',
  styleUrls: ['../app.component.css', './bound.component.css']
})
export class BoundComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div id="bound" class="container" v-highlight>
  <h1>Bound <img src="https://naver.github.io/egjs-flicking/images/bound-dog.png" width="40px" /></h1>
  <ul class="extra">
    <li>Bound the panels so that they are not out of the flicking area.</li>
    <li>This prevents unwanted free space within the flicking area.</li>
  </ul>
  <h2>bound: false</h2>
  <div class="hanger hanger0"></div>
  <eg-flicking class="flicking flicking0" [options]="{ gap: 10 }">
    <ng-template>
      <div class="panel"><div class="anchor"></div></div>
      <div class="panel"><div class="anchor"></div></div>
      <div class="panel"><div class="anchor"></div></div>
      <div class="panel"><div class="anchor"></div></div>
      <div class="panel"><div class="anchor"></div></div>
      <div class="panel"><div class="anchor"></div></div>
    </ng-template>
  </eg-flicking>
  <h2>bound: true</h2>
  <div class="hanger hanger0"></div>
  <eg-flicking class="flicking flicking1" [options]="{ gap: 10, bound: true }">
    <ng-template>
      <div class="panel"><div class="anchor"></div></div>
      <div class="panel"><div class="anchor"></div></div>
      <div class="panel"><div class="anchor"></div></div>
      <div class="panel"><div class="anchor"></div></div>
      <div class="panel"><div class="anchor"></div></div>
      <div class="panel"><div class="anchor"></div></div>
    </ng-template>
  </eg-flicking>
  <div class="pagination pagination2"></div>
  <pre><code class="hljs html" data-script="flicking1">{{ code1 }}</code></pre>
</div>
