// packages/vue-flicking/demo/features/PropChange.vue
<template>
  <div class="container">
    <flicking class="flicking" :options="{
      panelsPerView: this.panelsPerView,
      circular: false
    }">
      <div class="panel0"><div class="anchor"></div></div>
      <div class="panel1"><div class="anchor"></div></div>
      <div class="panel2"><div class="anchor"></div></div>
      <div class="panel3"><div class="anchor"></div></div>
      <div class="panel4"><div class="anchor"></div></div>
    </flicking>
    <button @click="onClick">Change</button>
  </div>
</template>
<script lang="ts">
import { Component, Vue } from "vue-property-decorator";

@Component({})
export default class PropChange extends Vue {
  public panelsPerView = 5;

  public onClick() {
    this.panelsPerView -= 1;
  }
}
</script>

// packages/ngx-flicking/projects/demo/src/app/propchange/propchange.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'demo-propchange',
  templateUrl: './propchange.component.html',
  styleUrls: ['../app.component.css']
})
export class PropChangeComponent {
  options = { panelsPerView: 5 };

  onClick() {
    this.options = {
      ...this.options,
      panelsPerView: this.options.panelsPerView - 1
    }
  }
}

<div class="container">
  <ngx-flicking class="flicking flicking0" [options]="options">
    <div flicking-panel class="panel panel0"></div>
    <div flicking-panel class="panel panel1"></div>
    <div flicking-panel class="panel panel2"></div>
    <div flicking-panel class="panel panel3"></div>
    <div flicking-panel class="panel panel4"></div>
  </ngx-flicking>
  <button (click)="onClick()">Change</button>
</div>
