// packages/vue-flicking/demo/features/component/PlaceHolderItem.vue
<template>
  <div class="infinite" :class="classes"></div>
</template>
<script lang="ts">
import { Component, Vue } from "vue-property-decorator";

@Component({
  props: {
    num: { type: Number },
  },
})
export default class PlaceHolder extends Vue {
  loaded = false;

  get classes() {
    return `panel${this.$props.num % 5} ${this.loaded ? "" : "placeholder"}`;
  }

  public mounted() {
    setTimeout(() => {
      this.loaded = true;
    }, 1500);
  }
}
</script>
<style scoped>

</style>

// packages/react-flicking/src/demo/features/PlaceHolderItem.tsx
import * as React from "react";

export default class PlaceHolderItem extends React.Component<{num: number}, {loaded: boolean}> {
  public state = {
    loaded: false,
  };
  public render() {
    const num = this.props.num;
    const loaded = this.state.loaded;
    return <div className={`infinite infinite${Math.abs(num) % 5} ${loaded ? "" : "placeholder"} flicking-panel`}>{num}</div>;
  }
  public componentDidMount() {
    setTimeout(() => {
      this.setState({loaded: true});
    }, 1500);
  }
}
